/******************************************************************************
Finite State Machine
Project: C-CNC
Description: Finite State Machine for the C-CNC controller

Generated by gv_fsm ruby gem, see https://rubygems.org/gems/gv_fsm
gv_fsm version 0.3.2
Generation date: 2022-05-20 09:51:35 +0200
Generated from: src/fsm.dot
The finite state machine has:
  7 states
  4 transition functions
Functions and types have been generated with prefix "ccnc_"
******************************************************************************/

#include "fsm.h"
#include "block.h"
#include "point.h"
#include <unistd.h>
#include <termios.h>

// Install signal handler: 
// SIGINT requests a transition to state stop
#include <signal.h>
static int _exit_request = 0;
static void signal_handler(int signal) {
  if (signal == SIGINT) {
    _exit_request = 1;
  }
}

// SEARCH FOR Your Code Here FOR CODE INSERTION POINTS!

// GLOBALS
// State human-readable names
const char *ccnc_state_names[] = {"init", "idle", "stop", "load_block", "no_motion", "rapid_motion", "interp_motion"};

// List of state functions
state_func_t *const ccnc_state_table[CCNC_NUM_STATES] = {
  ccnc_do_init,          // in state init
  ccnc_do_idle,          // in state idle
  ccnc_do_stop,          // in state stop
  ccnc_do_load_block,    // in state load_block
  ccnc_do_no_motion,     // in state no_motion
  ccnc_do_rapid_motion,  // in state rapid_motion
  ccnc_do_interp_motion, // in state interp_motion
};

// Table of transition functions
transition_func_t *const ccnc_transition_table[CCNC_NUM_STATES][CCNC_NUM_STATES] = {
  /* states:           init             , idle             , stop             , load_block       , no_motion        , rapid_motion     , interp_motion     */
  /* init          */ {NULL             , NULL             , NULL             , NULL             , NULL             , NULL             , NULL             }, 
  /* idle          */ {NULL             , NULL             , NULL             , ccnc_reset       , NULL             , NULL             , NULL             }, 
  /* stop          */ {NULL             , NULL             , NULL             , NULL             , NULL             , NULL             , NULL             }, 
  /* load_block    */ {NULL             , NULL             , NULL             , NULL             , NULL             , ccnc_begin_rapid , ccnc_begin_interp}, 
  /* no_motion     */ {NULL             , NULL             , NULL             , NULL             , NULL             , NULL             , NULL             }, 
  /* rapid_motion  */ {NULL             , NULL             , NULL             , ccnc_end_rapid   , NULL             , NULL             , NULL             }, 
  /* interp_motion */ {NULL             , NULL             , NULL             , NULL             , NULL             , NULL             , NULL             }, 
};

//  ____  _        _       
// / ___|| |_ __ _| |_ ___ 
// \___ \| __/ _` | __/ _ \
//  ___) | || (_| | ||  __/
// |____/ \__\__,_|\__\___|
//                         
//   __                  _   _                 
//  / _|_   _ _ __   ___| |_(_) ___  _ __  ___ 
// | |_| | | | '_ \ / __| __| |/ _ \| '_ \/ __|
// |  _| |_| | | | | (__| |_| | (_) | | | \__ \
// |_|  \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
//                                             

// Function to be executed in state init
// valid return states: CCNC_STATE_IDLE, CCNC_STATE_STOP
ccnc_state_t ccnc_do_init(ccnc_state_data_t *data) {
  ccnc_state_t next_state = CCNC_STATE_IDLE;
  point_t *sp, *zero;
  signal(SIGINT, signal_handler); 
  
  // Steps:
  // * in case of errors, transition to stop

  // * print software version
  eprintf("C-CNC ver. %s, %s build\n", VERSION, BUILD_TYPE);
  data->machine = machine_new(data->ini_file);
  // * connect with the machine
  if (!data->machine) {
    next_state = CCNC_STATE_STOP;
    goto next_state;
  }
  if (machine_connect(data->machine, NULL)) {
    next_state = CCNC_STATE_STOP;
    goto next_state;
  }

  // * load and parse the G-code file
  data->prog = program_new(data->prog_file);
  if (!data->prog) {
    next_state = CCNC_STATE_STOP;
    goto next_state;
  }
  if (program_parse(data->prog, data->machine) == EXIT_FAILURE) {
    next_state = CCNC_STATE_STOP;
    goto next_state;
  }
  // if available, calculate here the look-ahead

  // * print G-code file
  eprintf("Parsed the program %s\n", data->prog_file);
  program_print(data->prog, stderr);

  sp = machine_setpoint(data->machine);
  zero = machine_zero(data->machine);
  point_set_x(sp, point_x(zero));
  point_set_y(sp, point_y(zero));
  point_set_z(sp, point_z(zero));
  machine_sync(data->machine, 1);

  
next_state:
  switch (next_state) {
    case CCNC_STATE_IDLE:
    case CCNC_STATE_STOP:
      break;
    default:
      next_state = CCNC_NO_CHANGE;
  }
  
  return next_state;
}


// Function to be executed in state idle
// valid return states: CCNC_NO_CHANGE, CCNC_STATE_IDLE, CCNC_STATE_LOAD_BLOCK, CCNC_STATE_STOP
// SIGINT triggers an emergency transition to stop
ccnc_state_t ccnc_do_idle(ccnc_state_data_t *data) {
  ccnc_state_t next_state = CCNC_NO_CHANGE;
  char key;
  struct termios old_tio, new_tio;
  // Steps:
  // if q is pressed, switch to stop
  // * if spacebar is pressed, switch to load_block
  // * reset total timer
  eprintf("Press spacebar or 'r' to run, 'q' to quit\n");
  // save current terminal settings
  tcgetattr(STDIN_FILENO, &old_tio);
  // copy setting into new structure
  new_tio = old_tio;
  // disable caching 
  cfmakeraw(&new_tio);
  // set new settings
  tcsetattr(STDIN_FILENO, TCSANOW, &new_tio);
  // wait for keypress
  key = getchar();
  // reset initial temrinal setings
  tcsetattr(STDIN_FILENO, TCSANOW, &old_tio);
  switch (key)
  {
  case 'q':
  case 'Q':
    next_state = CCNC_STATE_STOP;
    break;
  case ' ':
  case 'r':
    next_state = CCNC_STATE_LOAD_BLOCK;
  default:
    break;
  }
  data->t_blk = 0;
  data->t_tot = 0;
  machine_listen_update(data->machine);
  
  switch (next_state) {
    case CCNC_NO_CHANGE:
    case CCNC_STATE_IDLE:
    case CCNC_STATE_LOAD_BLOCK:
    case CCNC_STATE_STOP:
      break;
    default:
      next_state = CCNC_NO_CHANGE;
  }
  
  // SIGINT transition override
  if (_exit_request) next_state = CCNC_STATE_STOP;
  
  return next_state;
}


// Function to be executed in state stop
// valid return states: CCNC_NO_CHANGE
ccnc_state_t ccnc_do_stop(ccnc_state_data_t *data) {
  ccnc_state_t next_state = CCNC_NO_CHANGE;
  
  // Steps:
  // * disconnect machine
  // * free resources
  eprintf("Clean up...");
  signal(SIGINT, SIG_DFL);
  if (data->machine) {
    machine_disconnect(data->machine);
    machine_free(data->machine);
  }
  if (data->prog) {
    program_free(data->prog);
  }
  eprintf(" done.\n");
  
  switch (next_state) {
    case CCNC_NO_CHANGE:
      break;
    default:
      next_state = CCNC_NO_CHANGE;
  }
  
  return next_state;
}


// Function to be executed in state load_block
// valid return states: CCNC_STATE_IDLE, CCNC_STATE_NO_MOTION, CCNC_STATE_RAPID_MOTION, CCNC_STATE_INTERP_MOTION
ccnc_state_t ccnc_do_load_block(ccnc_state_data_t *data) {
  ccnc_state_t next_state = CCNC_STATE_IDLE;
  
  // Steps:
  // * load next block/
  block_t *b = program_next(data->prog);
  if (!b) {
    next_state = CCNC_STATE_IDLE;
    goto next_state;
  }
  block_print(b, stderr);
  switch (block_type(b))
  {
  case NO_MOTION:
    next_state = CCNC_STATE_NO_MOTION;
    break;
  case RAPID:
    next_state = CCNC_STATE_RAPID_MOTION;
    break;
  case LINE:
  case ARC_CW:
  case ARC_CCW:
    next_state = CCNC_STATE_INTERP_MOTION;
    break;
  default:
    next_state = CCNC_STATE_IDLE;
    break;
  }
next_state:
  switch (next_state) {
    case CCNC_STATE_IDLE:
    case CCNC_STATE_NO_MOTION:
    case CCNC_STATE_RAPID_MOTION:
    case CCNC_STATE_INTERP_MOTION:
      break;
    default:
      next_state = CCNC_NO_CHANGE;
  }
  
  return next_state;
}


// Function to be executed in state no_motion
// valid return states: CCNC_STATE_LOAD_BLOCK
ccnc_state_t ccnc_do_no_motion(ccnc_state_data_t *data) {
  ccnc_state_t next_state = CCNC_STATE_LOAD_BLOCK;
  
  // Steps:
  // * print block command
  
  switch (next_state) {
    case CCNC_STATE_LOAD_BLOCK:
      break;
    default:
      next_state = CCNC_NO_CHANGE;
  }
  
  return next_state;
}


// Function to be executed in state rapid_motion
// valid return states: CCNC_NO_CHANGE, CCNC_STATE_LOAD_BLOCK, CCNC_STATE_RAPID_MOTION
// SIGINT triggers an emergency transition to stop
ccnc_state_t ccnc_do_rapid_motion(ccnc_state_data_t *data) {
  ccnc_state_t next_state = CCNC_NO_CHANGE;
  data_t tq = machine_tq(data->machine);
  // Steps:
  // * call machine_listen_update()
  // * update times (block and total)
  // * if error below threshold, transition to load_block
  machine_listen_update(data->machine);
  data->t_blk += tq;
  data->t_tot += tq;
  if (machine_error(data->machine) < machine_max_error(data->machine)) {
    next_state = CCNC_STATE_LOAD_BLOCK;
  }
  if (_exit_request) {
    _exit_request = 0;
    next_state = CCNC_STATE_LOAD_BLOCK;
  }

  switch (next_state) {
    case CCNC_NO_CHANGE:
    case CCNC_STATE_LOAD_BLOCK:
    case CCNC_STATE_RAPID_MOTION:
      break;
    default:
      next_state = CCNC_NO_CHANGE;
  }
  
  // SIGINT transition override
  if (_exit_request) next_state = CCNC_STATE_STOP;
  
  return next_state;
}


// Function to be executed in state interp_motion
// valid return states: CCNC_NO_CHANGE, CCNC_STATE_LOAD_BLOCK, CCNC_STATE_INTERP_MOTION
// SIGINT triggers an emergency transition to stop
ccnc_state_t ccnc_do_interp_motion(ccnc_state_data_t *data) {
  ccnc_state_t next_state = CCNC_NO_CHANGE;
  data_t tq = machine_tq(data->machine);
  data_t lambda, feed;
  block_t *b = program_current(data->prog);
  point_t *sp;

  // Steps:
  // * calculate lambda
  // * interpolate position
  // * update times
  // * if lambda >= 1 transition to load_block
  data->t_blk += tq;
  data->t_tot += tq;
  if (data->t_blk >= block_dt(b) + tq / 2.0) {
    next_state = CCNC_STATE_LOAD_BLOCK;
    goto next_block;
  }
  lambda = block_lambda(b, data->t_blk, &feed);
  sp = block_interpolate(b, lambda);
  if (!sp) {
    next_state = CCNC_STATE_LOAD_BLOCK;
    goto next_block;
  }
  printf("%lu,%f,%f,%f,%f,%f,%f,%f,%f\n", block_n(b), data->t_tot, data->t_blk, lambda, lambda * block_length(b), feed, point_x(sp), point_y(sp), point_z(sp));
  machine_sync(data->machine, 0);

next_block:
  switch (next_state) {
    case CCNC_NO_CHANGE:
    case CCNC_STATE_LOAD_BLOCK:
    case CCNC_STATE_INTERP_MOTION:
      break;
    default:
      next_state = CCNC_NO_CHANGE;
  }
  
  // SIGINT transition override
  if (_exit_request) next_state = CCNC_STATE_STOP;
  
  return next_state;
}


//  _____                    _ _   _              
// |_   _| __ __ _ _ __  ___(_) |_(_) ___  _ __   
//   | || '__/ _` | '_ \/ __| | __| |/ _ \| '_ \
//   | || | | (_| | | | \__ \ | |_| | (_) | | | | 
//   |_||_|  \__,_|_| |_|___/_|\__|_|\___/|_| |_| 
//                                                
//   __                  _   _                 
//  / _|_   _ _ __   ___| |_(_) ___  _ __  ___ 
// | |_| | | | '_ \ / __| __| |/ _ \| '_ \/ __|
// |  _| |_| | | | | (__| |_| | (_) | | | \__ \
// |_|  \__,_|_| |_|\___|\__|_|\___/|_| |_|___/
//    
                                         
// This function is called in 1 transition:
// 1. from idle to load_block
void ccnc_reset(ccnc_state_data_t *data) {
  // Steps:
  // reset both timers
  data->t_blk = data->t_tot = 0;
  printf("n,t_tot,t_blk,lambda,s,feed,x,y,z\n");
}

// This function is called in 1 transition:
// 1. from load_block to rapid_motion
void ccnc_begin_rapid(ccnc_state_data_t *data) {
  point_t *sp = machine_setpoint(data->machine);
  block_t *b = program_current(data->prog);
  point_t *target = block_target(b);
  // Steps:
  // * reset block timer
  // * set final position as set point and use machine_sync
  // * call machine_listen_start()
  machine_listen_start(data->machine);
  data->t_blk = 0;
  // copy target coordinates into setpoint
  point_set_x(sp, point_x(target));
  point_set_y(sp, point_y(target));
  point_set_z(sp, point_z(target));
  machine_sync(data->machine, 1);
}

// This function is called in 1 transition:
// 1. from load_block to interp_motion
void ccnc_begin_interp(ccnc_state_data_t *data) {
  // Steps:
  // reset block timer
  data->t_blk = 0;
}

// This function is called in 1 transition:
// 1. from rapid_motion to load_block
void ccnc_end_rapid(ccnc_state_data_t *data) {
  // Steps:
  // * call machine_listen_stop()
  machine_listen_stop(data->machine);
}


//  ____  _        _        
// / ___|| |_ __ _| |_ ___  
// \___ \| __/ _` | __/ _ \
//  ___) | || (_| | ||  __/ 
// |____/ \__\__,_|\__\___| 
//                          
//                                              
//  _ __ ___   __ _ _ __   __ _  __ _  ___ _ __ 
// | '_ ` _ \ / _` | '_ \ / _` |/ _` |/ _ \ '__|
// | | | | | | (_| | | | | (_| | (_| |  __/ |   
// |_| |_| |_|\__,_|_| |_|\__,_|\__, |\___|_|   
//                              |___/           

ccnc_state_t ccnc_run_state(ccnc_state_t cur_state, ccnc_state_data_t *data) {
  ccnc_state_t new_state = ccnc_state_table[cur_state](data);
  if (new_state == CCNC_NO_CHANGE) new_state = cur_state;
  transition_func_t *transition = ccnc_transition_table[cur_state][new_state];
  if (transition)
    transition(data);
  return new_state == CCNC_NO_CHANGE ? cur_state : new_state;
};

#ifdef TEST_MAIN
#include <unistd.h>
int main() {
  ccnc_state_t cur_state = CCNC_STATE_INIT;
  do {
    cur_state = ccnc_run_state(cur_state, NULL);
    sleep(1);
  } while (cur_state != CCNC_STATE_STOP);
  ccnc_run_state(cur_state, NULL);
  return 0;
}
#endif
